export type RoleType = 'paid' | 'free';

export enum BasicPermission {
  CREATE_EDIT_PEOPLE_AND_TEAMS = 'CREATE_EDIT_PEOPLE_AND_TEAMS',
  CREATE_EDIT_CATEGORIES = 'CREATE_EDIT_CATEGORIES',
  DELETE_WORK_ORDERS = 'DELETE_WORK_ORDERS',
  DELETE_LOCATIONS = 'DELETE_LOCATIONS',
  DELETE_PREVENTIVE_MAINTENANCE_TRIGGERS = 'DELETE_PREVENTIVE_MAINTENANCE_TRIGGERS',
  DELETE_ASSETS = 'DELETE_ASSETS',
  DELETE_PARTS_AND_MULTI_PARTS = 'DELETE_PARTS_AND_MULTI_PARTS',
  DELETE_PURCHASE_ORDERS = 'DELETE_PURCHASE_ORDERS',
  DELETE_METERS = 'DELETE_METERS',
  DELETE_VENDORS_AND_CUSTOMERS = 'DELETE_VENDORS_AND_CUSTOMERS',
  DELETE_CATEGORIES = 'DELETE_CATEGORIES',
  DELETE_FILES = 'DELETE_FILES',
  DELETE_PEOPLE_AND_TEAMS = 'DELETE_PEOPLE_AND_TEAMS',
  ACCESS_SETTINGS = 'ACCESS_SETTINGS'
}

export type RoleCode =
  | 'ADMIN'
  | 'LIMITED_ADMIN'
  | 'TECHNICIAN'
  | 'LIMITED_TECHNICIAN'
  | 'VIEW_ONLY'
  | 'REQUESTER'
  | 'USER_CREATED';
export interface Role {
  id: number;
  name: string;
  users: number;
  externalId?: string;
  description?: string;
  type: RoleType;
  code: RoleCode;
  permissions: BasicPermission[];
}
